help([[Caffe deps, modified from TACC stampede caffe module]])
whatis("Name: caffe-deps")
whatis("Version: 1.1.4")
family("caffe")

local base_dir = "/home1/04446/tg837458/Workspaces/awnn_workspace/intel-caffe-deprecated/caffe/.build_release"

prepend_path("PATH", pathJoin( base_dir , "tools"))
prepend_path("LD_LIBRARY_PATH", pathJoin( base_dir , "lib"))
prepend_path("PYTHONPATH","/opt/apps/intel18/impi18_0/caffe/1.1.4/python")
prepend_path("PYTHONPATH","/opt/apps/intel18/impi18_0/caffe/1.1.4/libraries/mlsl/intel64/include")
prepend_path("LD_LIBRARY_PATH","/opt/apps/intel18/impi18_0/caffe/1.1.4/libraries/gflags/lib")
prepend_path("LD_LIBRARY_PATH","/opt/apps/intel18/impi18_0/caffe/1.1.4/libraries/glog/lib")
prepend_path("LD_LIBRARY_PATH","/opt/apps/intel18/impi18_0/caffe/1.1.4/libraries/leveldb/lib")
prepend_path("LD_LIBRARY_PATH","/opt/apps/intel18/impi18_0/caffe/1.1.4/libraries/lmdb/lib")
prepend_path("LD_LIBRARY_PATH","/opt/apps/intel18/impi18_0/caffe/1.1.4/libraries/mlsl/intel64/lib")
prepend_path("LD_LIBRARY_PATH","/opt/apps/intel18/impi18_0/caffe/1.1.4/libraries/opencv/lib")
-- FengLi's installation, the one in default didn't work
prepend_path("LD_LIBRARY_PATH","/home1/04446/tg837458/software/install/lib")
prepend_path("LD_LIBRARY_PATH","/opt/apps/intel18/impi18_0/caffe/1.1.4/libraries/snappy/lib")
prepend_path("LD_LIBRARY_PATH","/opt/apps/intel18/impi18_0/caffe/1.1.4/libraries/mklml/lib")
prepend_path("LD_LIBRARY_PATH","/opt/apps/intel18/impi18_0/caffe/1.1.4/libraries/mkldnn/lib")
prepend_path("LD_LIBRARY_PATH","/opt/apps/intel18/impi18_0/caffe/1.1.4/libraries/dlcp/lib")
prepend_path("MODULEPATH","/opt/apps/bar1_1/modulefiles")
setenv("TACC_CAFFE_DIR","/opt/apps/intel18/impi18_0/caffe/1.1.4")
setenv("TACC_CAFFE_INC","/opt/apps/intel18/impi18_0/caffe/1.1.4/include")
setenv("TACC_CAFFE_LIB","/opt/apps/intel18/impi18_0/caffe/1.1.4/lib")
setenv("TACC_CAFFE_BIN","/opt/apps/intel18/impi18_0/caffe/1.1.4/bin")
setenv("MLSL_ROOT","/opt/apps/intel18/impi18_0/caffe/1.1.4/libraries/mlsl")
load("hdf5/1.8.16")
load("boost/1.65")
prepend_path("LD_LIBRARY_PATH","/opt/apps/intel18/impi18_0/caffe/1.1.4/libraries/boost/lib")
